/* Auto-generated by genmsg_cpp for file /home/patrick/catkin_ws/src/drcsim/ros/atlas_msgs/msg/AtlasBehaviorPelvisServoParams.msg */
#ifndef ATLAS_MSGS_MESSAGE_ATLASBEHAVIORPELVISSERVOPARAMS_H
#define ATLAS_MSGS_MESSAGE_ATLASBEHAVIORPELVISSERVOPARAMS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace atlas_msgs
{
template <class ContainerAllocator>
struct AtlasBehaviorPelvisServoParams_ {
  typedef AtlasBehaviorPelvisServoParams_<ContainerAllocator> Type;

  AtlasBehaviorPelvisServoParams_()
  : pelvis_height(0.0)
  , pelvis_yaw(0.0)
  , pelvis_lat(0.0)
  {
  }

  AtlasBehaviorPelvisServoParams_(const ContainerAllocator& _alloc)
  : pelvis_height(0.0)
  , pelvis_yaw(0.0)
  , pelvis_lat(0.0)
  {
  }

  typedef double _pelvis_height_type;
  double pelvis_height;

  typedef double _pelvis_yaw_type;
  double pelvis_yaw;

  typedef double _pelvis_lat_type;
  double pelvis_lat;


  typedef boost::shared_ptr< ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator>  const> ConstPtr;
}; // struct AtlasBehaviorPelvisServoParams
typedef  ::atlas_msgs::AtlasBehaviorPelvisServoParams_<std::allocator<void> > AtlasBehaviorPelvisServoParams;

typedef boost::shared_ptr< ::atlas_msgs::AtlasBehaviorPelvisServoParams> AtlasBehaviorPelvisServoParamsPtr;
typedef boost::shared_ptr< ::atlas_msgs::AtlasBehaviorPelvisServoParams const> AtlasBehaviorPelvisServoParamsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace atlas_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> > {
  static const char* value() 
  {
    return "82f59d8aa26e61afaf2c8dbb7b4e7856";
  }

  static const char* value(const  ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x82f59d8aa26e61afULL;
  static const uint64_t static_value2 = 0xaf2c8dbb7b4e7856ULL;
};

template<class ContainerAllocator>
struct DataType< ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> > {
  static const char* value() 
  {
    return "atlas_msgs/AtlasBehaviorPelvisServoParams";
  }

  static const char* value(const  ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# mirrored from AtlasControlTypes.h\n\
\n\
float64 pelvis_height\n\
float64 pelvis_yaw\n\
float64 pelvis_lat\n\
\n\
";
  }

  static const char* value(const  ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pelvis_height);
    stream.next(m.pelvis_yaw);
    stream.next(m.pelvis_lat);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AtlasBehaviorPelvisServoParams_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> & v) 
  {
    s << indent << "pelvis_height: ";
    Printer<double>::stream(s, indent + "  ", v.pelvis_height);
    s << indent << "pelvis_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.pelvis_yaw);
    s << indent << "pelvis_lat: ";
    Printer<double>::stream(s, indent + "  ", v.pelvis_lat);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ATLAS_MSGS_MESSAGE_ATLASBEHAVIORPELVISSERVOPARAMS_H

