/* Auto-generated by genmsg_cpp for file /home/patrick/catkin_ws/src/drcsim/ros/atlas_msgs/msg/AtlasBehaviorStandFeedback.msg */
#ifndef ATLAS_MSGS_MESSAGE_ATLASBEHAVIORSTANDFEEDBACK_H
#define ATLAS_MSGS_MESSAGE_ATLASBEHAVIORSTANDFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace atlas_msgs
{
template <class ContainerAllocator>
struct AtlasBehaviorStandFeedback_ {
  typedef AtlasBehaviorStandFeedback_<ContainerAllocator> Type;

  AtlasBehaviorStandFeedback_()
  : status_flags(0)
  {
  }

  AtlasBehaviorStandFeedback_(const ContainerAllocator& _alloc)
  : status_flags(0)
  {
  }

  typedef uint32_t _status_flags_type;
  uint32_t status_flags;


  typedef boost::shared_ptr< ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator>  const> ConstPtr;
}; // struct AtlasBehaviorStandFeedback
typedef  ::atlas_msgs::AtlasBehaviorStandFeedback_<std::allocator<void> > AtlasBehaviorStandFeedback;

typedef boost::shared_ptr< ::atlas_msgs::AtlasBehaviorStandFeedback> AtlasBehaviorStandFeedbackPtr;
typedef boost::shared_ptr< ::atlas_msgs::AtlasBehaviorStandFeedback const> AtlasBehaviorStandFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace atlas_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "db5aeaf3d00b862980dcbc6b5cfc70fc";
  }

  static const char* value(const  ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdb5aeaf3d00b8629ULL;
  static const uint64_t static_value2 = 0x80dcbc6b5cfc70fcULL;
};

template<class ContainerAllocator>
struct DataType< ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "atlas_msgs/AtlasBehaviorStandFeedback";
  }

  static const char* value(const  ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# mirrored from AtlasControlTypes.h\n\
uint32 status_flags    # use AtlasBeahviorStandFlags\n\
\n\
";
  }

  static const char* value(const  ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.status_flags);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AtlasBehaviorStandFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::atlas_msgs::AtlasBehaviorStandFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "status_flags: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.status_flags);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ATLAS_MSGS_MESSAGE_ATLASBEHAVIORSTANDFEEDBACK_H

