/* Auto-generated by genmsg_cpp for file /home/patrick/catkin_ws/src/drcsim/ros/atlas_msgs/msg/AtlasBehaviorManipulateFeedback.msg */
#ifndef ATLAS_MSGS_MESSAGE_ATLASBEHAVIORMANIPULATEFEEDBACK_H
#define ATLAS_MSGS_MESSAGE_ATLASBEHAVIORMANIPULATEFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "atlas_msgs/AtlasBehaviorPelvisServoParams.h"

namespace atlas_msgs
{
template <class ContainerAllocator>
struct AtlasBehaviorManipulateFeedback_ {
  typedef AtlasBehaviorManipulateFeedback_<ContainerAllocator> Type;

  AtlasBehaviorManipulateFeedback_()
  : status_flags(0)
  , clamped()
  {
  }

  AtlasBehaviorManipulateFeedback_(const ContainerAllocator& _alloc)
  : status_flags(0)
  , clamped(_alloc)
  {
  }

  typedef uint32_t _status_flags_type;
  uint32_t status_flags;

  typedef  ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator>  _clamped_type;
   ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator>  clamped;


  typedef boost::shared_ptr< ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator>  const> ConstPtr;
}; // struct AtlasBehaviorManipulateFeedback
typedef  ::atlas_msgs::AtlasBehaviorManipulateFeedback_<std::allocator<void> > AtlasBehaviorManipulateFeedback;

typedef boost::shared_ptr< ::atlas_msgs::AtlasBehaviorManipulateFeedback> AtlasBehaviorManipulateFeedbackPtr;
typedef boost::shared_ptr< ::atlas_msgs::AtlasBehaviorManipulateFeedback const> AtlasBehaviorManipulateFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace atlas_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "81c353ff9e8def49f995ee851f13f670";
  }

  static const char* value(const  ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x81c353ff9e8def49ULL;
  static const uint64_t static_value2 = 0xf995ee851f13f670ULL;
};

template<class ContainerAllocator>
struct DataType< ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "atlas_msgs/AtlasBehaviorManipulateFeedback";
  }

  static const char* value(const  ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# mirrored from AtlasControlTypes.h\n\
uint32 status_flags    # use AtlasBeahviorManipulateFlags\n\
atlas_msgs/AtlasBehaviorPelvisServoParams clamped\n\
\n\
================================================================================\n\
MSG: atlas_msgs/AtlasBehaviorPelvisServoParams\n\
# mirrored from AtlasControlTypes.h\n\
\n\
float64 pelvis_height\n\
float64 pelvis_yaw\n\
float64 pelvis_lat\n\
\n\
";
  }

  static const char* value(const  ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.status_flags);
    stream.next(m.clamped);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AtlasBehaviorManipulateFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::atlas_msgs::AtlasBehaviorManipulateFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "status_flags: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.status_flags);
    s << indent << "clamped: ";
s << std::endl;
    Printer< ::atlas_msgs::AtlasBehaviorPelvisServoParams_<ContainerAllocator> >::stream(s, indent + "  ", v.clamped);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ATLAS_MSGS_MESSAGE_ATLASBEHAVIORMANIPULATEFEEDBACK_H

